#!/bin/sh

SRCDIR=`dirname $0 | xargs readlink -f`

NAME=${1:-*.patch}
PERL_BASE=perl-5.16.2

if [ ! -e ${SRCDIR}/${PERL_BASE}.tar.gz ]; then
    echo Please put ${PERL_BASE}.tar.gz in $SRCDIR >&2
    exit 255
fi

WRKDIR=`pwd`

cd $WRKDIR

echo Extracting perl
if [ -e ${PERL_BASE} ]; then
    mv -f ${PERL_BASE} old; rm -rf old &
fi
tar xzf "${SRCDIR}/${PERL_BASE}.tar.gz"
cd ${PERL_BASE}

echo Copying local files
cp -Rf ${SRCDIR}/files/* ./

echo Applying local patches
find ${SRCDIR}/patches/GOOD -name '*.patch' -print -exec patch -Ep0 -i {} \;
