#!/bin/sh

SRCDIR=`dirname $0 | xargs readlink -f`

NAME=${1:-*.patch}
PERL_BASE=perl-5.16.2

if [ ! -e ${SRCDIR}/${PERL_BASE}.tar.gz ]; then
    echo Please put ${PERL_BASE}.tar.gz in $SRCDIR >&2
    exit 255
fi

WRKDIR=`pwd`

mkdir -p /tmp/buildlogs
find ${SRCDIR}/patches/RESEARCH -name $NAME | {
    while read patch; do
	echo Testing $patch

        cd $WRKDIR
        log=/tmp/buildlogs/`basename $patch`.log

        echo Extracting perl
        if [ -e ${PERL_BASE} ]; then
            mv -f ${PERL_BASE} old; rm -rf old &
        fi
        tar xzf "${SRCDIR}/${PERL_BASE}.tar.gz"
        cd ${PERL_BASE}

        echo Applying $patch
        patch -Ep0 -F 10 -Ni "$patch" >$log 2>&1 || continue

        new_patch=`echo "$patch" | sed -e 's/RESEARCH/APPLIES/'`
        new_dir=`dirname "$new_patch"`
        mkdir -p "$new_dir"

        echo Generating $new_patch
        find . -name '*.orig' | (
            while read o; do
                diff -u $o ${o%.orig}
            done
        ) > "${new_patch}.new"

        echo Copying local files
        cp -Rf ${SRCDIR}/files/* ./

        echo Applying local patches
        find ${SRCDIR}/patches/GOOD -name '*.patch' -print \
            -exec patch -Ep0 -i {} \; | tee -a $log

        echo Configuring
        sh ./Configure -de 2>&1 | tee -a $log

        echo Building
        make 2>&1 | tee -a $log

        echo Testing
        make test 2>&1 | tee -a $log

        echo Renaming patches
        mv -f "$patch" "$patch.old"
        patch="$new_patch"

        # Did we win?
        status=`tail -2 $log | head -1`
        if [ "$status" == "All tests successful." ]; then
            new_patch=`echo "$patch" | sed -e 's/APPLIES/GOOD/'`

            new_dir=`dirname "$new_patch"`
            mkdir -p "$new_dir"

            mv -f "$patch.new" "$new_patch"
	    patch="$new_patch"
	else
	    mv -f "${patch}.new" "$patch"
        fi

	echo Patch is now $patch
    done
}
