#!/usr/bin/perl
use strict;
use diagnostics;

use List::Util qw(max);

my $fh;
while (<>) {
	# obviously will fail on filenames with spaces, but whatev
	if ( my ($first, $second) = /^diff.*?(\S+)\s+(\S+)$/ ) {
		close $fh if $fh;

		my @f = split m{/}, $first;
		my @s = split m{/}, $second;

		my @p;
		while ($f[-1] eq $s[-1]) {
			unshift @p, pop @f;
			pop @s;
		}

		my $path = join '_', @p;
		print "$path\n";
		open $fh, '>', 'patches/' . $path . '.patch' or die "Unable to open $path: $!";
	}
	print $fh $_ if $fh;
}
